#- set_fact:
#    router_lb_ip: "{{ hostvars['localhost']['router_lb_ip'] }}"
#    registry_storage_account_key: "{{  hostvars['localhost']['registry_storage_account_key'] }}"
- name: add bastion host
  add_host:
    name: "{{ rg }}b.{{ location }}.cloudapp.azure.com"
    groups: bastions
    ansible_user: "{{ admin_user }}"
    ansible_become: True

# The Azure VMs are provisioned asynchronously. It can take some time
# until they are reachable via SSH, even after Azure reports that the
# provisioning state is "Succeeded".
- name: Wait for bastion to become reachable via SSH
  wait_for_connection:
    sleep: 30
    timeout: 1200
    connect_timeout: 10
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion RHSM increase timeout
  lineinfile:
    dest: /etc/rhsm/rhsm.conf
    line: 'server_timeout=600'
    insertafter: '^proxy_password ='
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion RHSM unregister
  redhat_subscription:
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion RHSM Activation Key
  redhat_subscription:
    state: "{{ state }}"
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  delegate_to: "{{ groups['bastions'][0] }}"
  when:
    - rhsm_key is defined and rhsm_key != ""
    - rhsm_org is defined and rhsm_org != ""

- name: Azure | Bastion RHSM Username - Password
  redhat_subscription:
    state: "{{ state }}"
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  delegate_to: "{{ groups['bastions'][0] }}"
  when:
    - rhsm_user is defined and rhsm_user != ""
    - rhsm_pass is defined and rhsm_pass != ""

- name: Azure | Bastion disable all repos
  rhsm_repository:
    name: '*'
    state: disabled
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion enable repos
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: enabled
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion install required packages
  yum:
    name: "{{ bastion_pkgs }}"
    state: present
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion template ansible hosts
  template:
    src: hosts.j2
    dest: hosts
    backup: yes
  delegate_to: "{{ groups['bastions'][0] }}"

- name: Azure | Bastion copy files
  copy:
    src: ansible.cfg
    dest: ansible.cfg
  delegate_to: "{{ groups['bastions'][0] }}"

- block:
    - name: Azure | Add ocpadmin group
      group:
        name: ocpadmin
      delegate_to: "{{ groups['bastions'][0] }}"

    - name: Allow password-less sudo for ocpadmin group
      copy:
        dest: /etc/sudoers.d/ocpadmin
        content: "%ocpadmin        ALL=(ALL)       NOPASSWD: ALL"
      delegate_to: "{{ groups['bastions'][0] }}"

    - name: Azure | Add local user
      user:
        name: "{{ item.key }}"
        groups: ocpadmin
        append: yes
      delegate_to: "{{ groups['bastions'][0] }}"
      with_dict: "{{ bastion_users }}"

    - name: Azure | Add authorized key
      authorized_key:
        user: "{{ item.key }}"
        key: "{{ item.value }}"
      delegate_to: "{{ groups['bastions'][0] }}"
      with_dict: "{{ bastion_users }}"
  when: bastion_users != {}

- block:
    - name: Azure | Install dnsmasq
      yum:
        name: dnsmasq
        state: installed
      delegate_to: "{{ groups['bastions'][0] }}"

    - name: Azure | Configure private dnsmasq domain
      template:
        src: private-dnsmasq.conf.j2
        dest: /etc/dnsmasq.d/private-dnsmasq.conf
      delegate_to: "{{ groups['bastions'][0] }}"
      notify: Restart dnsmasq

    - name: Azure | Get upstream nameserver
      shell: grep '^nameserver ' /etc/resolv.conf | awk '{ print $2 }'
      register: cmd
      delegate_to: "{{ groups['bastions'][0] }}"

    - set_fact:
        upstream_dns: "{{ cmd.stdout }}"

    - name: Azure | Update resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: "^nameserver "
        line: "nameserver 127.0.0.1"
      delegate_to: "{{ groups['bastions'][0] }}"

    - name: Azure | Create origin-dns.conf
      copy:
        content: |
          no-resolv
          domain-needed
          no-negcache
          max-cache-ttl=1
          enable-dbus
          bind-interfaces
          listen-address=127.0.0.1
        dest: /etc/dnsmasq.d/origin-dns.conf
      delegate_to: "{{ groups['bastions'][0] }}"
      notify: Restart dnsmasq

    - name: Azure | Create origin-upstream-dns.conf
      copy:
        content: server={{ upstream_dns }}
        dest: /etc/dnsmasq.d/origin-upstream-dns.conf
      delegate_to: "{{ groups['bastions'][0] }}"
      notify: Restart dnsmasq
      when: upstream_dns != '127.0.0.1'
  when: dns_domain_nameservers is defined
